% Link: https://www.mathworks.com/help/dsp/ref/dsp.colorednoise-system-object.html

pinkNoise = dsp.ColoredNoise('pink',1024,2);
sa = spectrumAnalyzer(SpectrumType='power-density',...
    Method='welch',...
    AveragingMethod='exponential',...
    ForgettingFactor=0.95,...
    OverlapPercent=50,Window='hamming',...
    PlotAsTwoSidedSpectrum=false, ...
    FrequencyScale='log',YLimits=[-50 30]);

% Run the simulation for 30 seconds.

tic
while toc < 30
    pink = pinkNoise();      
    sa(pink);
end